### ISSUE TITLE
Failed to compile and deploy Erlang app under Windows Environment

### ISSUE THREAD

**Issue by jazzystring1** [madcat78/cowboy-websocket-example#1]
@madcat78 I recently used your build pack under Windows Environment but I was encountering a problem deploying my app to heroku. Here is the log

```
-----> Erlang app detected

-----> Stack is heroku-16

-----> Using Erlang/OTP-20.1

-------> Fetching Erlang/OTP-20.1

-------> Finished fetching tarball, checking

-------> Unpacking Erlang/OTP OTP-20.1

-------> Installing Erlang/OTP OTP-20.1

-----> Building release with Rebar3

/app/tmp/buildpacks/e900d89bb2c76dd26822be57a51fef4328f7f1636df28aab8125c7175298205aec61ebb51794363f643dd1b363beaffcddc03369f099debf7c430a58943ef5db/bin/compile: line 181: ./rebar3: Permission denied

 !     Push rejected, failed to compile Erlang app.

 !     Push failed
```

I'm using rebar3 as my build tool.

**Comment by madcat78** [comment]
You probably added a Windows version of rebar3 to the main folder and pushed it to Heroku.
Remove it (using git) and push it again.
The Heroku buildpack checks what tool you are using and adds it automatically to build your project.

**Comment by jazzystring1** [comment]
You mean removing the rebar3 and rebar3.cmd in my app directory?

**Comment by madcat78** [comment]
Yes. Heroku will download and use a rebar3 executable for Linux (Heroku uses Ubuntu). You don't need to include that in your app.

**Comment by jazzystring1** [comment]
Thank you for the reply but I got new error deploying my app to heroku. Here is the log

```
-----> Erlang app detected

-----> Stack is heroku-16

-----> Using Erlang/OTP-20.1 

/app/tmp/buildpacks/4407351525d345b5e0e0d71a4e32c88b64d2723e2eccd5e8e3e3c71d9b93149f7d9180aff97076dd9b2e54e7b648030f3789026034d7434dc6c8050d90ad412a/bin/compile: line 122: test: /app/tmp/cache/OTP-20.1: binary operator expected

-------> Fetching Erlang/OTP-20.1 

curl: (6) Could not resolve host: .tgz

 !     Push rejected, failed to compile Erlang app.

 !     Push failed
```

**Comment by madcat78** [comment]
I'm sorry but I'm unable to reproduce your errors. I've set up a Windows environment and it worked fine at the very first attempt.
Start from scratch and follow the instructions without making any changes.

**Comment by jazzystring1** [comment]
Ohhh, okay let me try maybe I was too doing this bad. Here's what I did actually.

1. In my app directory, i type "git init"
2. "git add *"
3. git commit -m "My first commit"
4. heroku login
4. heroku create APP_NAME
5. Added your buildpack
6. echo OTP-20.1 > .preferred_otp_version
7. git config user.name = "jazzy"
8. git config user.email = "myedmailaddress"
9. git commit -m "Select 20.1 as preferred OTP version" -a
10. git push heroku master

And before i did this, i removed rebar and rebar3.cmd using git. Did i miss something throughout my steps? Thank you for your kind replies :)

**Comment by jazzystring1** [comment]
Nvm, I solved my problem! :D Thanks for your wonderful buildpack. Hope to be like you someday hehe
